# you can use the following aliases
# * {base_path} = application base path

tcp_server:
  host: localhost
  port: 11100

particle_io:
  access_token: ae63704ab514f24a9d54f5dab948f0f6248d58a3

proxies:
  http: http://192.168.150.153:8080
  https: https://192.168.150.153:8080

flask:
  WTF_CSRF_ENABLED: True
  SECRET_KEY: 2cVkwR1IjeMJjZhepkNc

database:
  SQLALCHEMY_DATABASE_URI: 'sqlite:///{base_path}app.db'
  SQLALCHEMY_MIGRATE_REPO: '{base_path}db_repository'
  SQLALCHEMY_TRACK_MODIFICATIONS: True


